export const Routes = {
  LOGIN: '/',
  SIGN_UP: '/sign-up',
  WELCOME: '/welcome',
  HOME: '/home',
  INVITE: '/invite',
  EDIT_PROFILE: '/edit-profile',
  UPDATE_EDIT_GUARDIANS: '/update/edit-guardians',
  UPDATE_ADD_EMAIL: '/update/add-email',
  UPDATE_VERIFY_EMAIL: '/update/verify-email',
  UPDATE_CONFIRM_GUARDIANS: '/update/confirm-guardians',
  UPDATE_PASSWORD: '/update/password',
  ACTIVITY: '/activity',
  ONBOARD_RECOVERY: '/onboard/recovery',
  ONBOARD_ADD_EMAIL: '/onboard/add-email',
  ONBOARD_VERIFY_EMAIL: '/onboard/verify-email',
  ONBOARD_SUMMARY: '/onboard/summary',
  RECOVER_LOOKUP: '/recover/lookup',
  RECOVER_NEW_PASSWORD: '/recover/new-password',
  RECOVER_NOT_POSSIBLE: '/recover/not-possible',
  RECOVER_VERIFY_EMAIL: '/recover/verify-email',
  RECOVER_STATUS: '/recover/status',
  RECOVER_APPROVE_REQUEST: 'recover/approve-request',
  RECOVER_CONFIRM: '/recover/confirm',
};
