export const Routes = {
  LOGIN: '/',
  SIGN_UP: '/sign-up',
  WELCOME: '/welcome',
  HOME: '/home',
  EDIT_PROFILE: '/edit-profile',
  EDIT_PASSWORD: '/edit-password',
  EDIT_EMAIL: '/edit-email',
  ACTIVITY: '/activity',
  ONBOARD_RECOVERY: '/onboard/recovery',
  ONBOARD_ADD_EMAIL: '/onboard/add-email',
  ONBOARD_VERIFY_EMAIL: '/onboard/verify-email',
  ONBOARD_SUMMARY: '/onboard/summary',
  RECOVER_LOOKUP: '/recover/lookup',
  RECOVER_NEW_PASSWORD: '/recover/new-password',
  RECOVER_NOT_POSSIBLE: '/recover/not-possible',
  RECOVER_VERIFY_EMAIL: '/recover/verify-email',
  RECOVER_STATUS: '/recover/status',
  RECOVER_SUBMIT: '/recover/submit',
};
