import {ImageSourcePropType} from 'react-native';

export const EmailLogo: ImageSourcePropType = require('../../assets/images/email-logo.png');
export const EthereumLogo: ImageSourcePropType = require('../../assets/images/ethereum-logo.png');
export const FingerprintLogo: ImageSourcePropType = require('../../assets/images/fingerprint-logo.png');
export const LockLogo: ImageSourcePropType = require('../../assets/images/lock-logo.png');
export const PolygonLogo: ImageSourcePropType = require('../../assets/images/polygon-logo.png');
export const Saly10Illustration: ImageSourcePropType = require('../../assets/images/saly-10-illustration.png');
export const Saly12Illustration: ImageSourcePropType = require('../../assets/images/saly-12-illustration.png');
export const Saly26Illustration: ImageSourcePropType = require('../../assets/images/saly-26-illustration.png');
export const Saly31Illustration: ImageSourcePropType = require('../../assets/images/saly-31-illustration.png');
export const Saly43Illustration: ImageSourcePropType = require('../../assets/images/saly-43-illustration.png');
export const ShieldWithCheckLogo: ImageSourcePropType = require('../../assets/images/shield-with-check-logo.png');
export const UsdLogo: ImageSourcePropType = require('../../assets/images/usd-logo.png');
export const WalletConnectLogo: ImageSourcePropType = require('../../assets/images/walletconnect-logo.png');
export const BitcoinLogo: ImageSourcePropType = require('../../assets/images/bitcoin-logo.png');
export const UNIlogo: ImageSourcePropType = require('../../assets/images/uni-logo.png');
export const AAVElogo: ImageSourcePropType = require('../../assets/images/aave-logo.png');
export const CRVlogo: ImageSourcePropType = require('../../assets/images/crv-logo.png');
export const LDOlogo: ImageSourcePropType = require('../../assets/images/ldo-logo.png');
export const LINKlogo: ImageSourcePropType = require('../../assets/images/link-logo.png');
export const MKRlogo: ImageSourcePropType = require('../../assets/images/mkr-logo.png');
export const DAIlogo: ImageSourcePropType = require('../../assets/images/dai-logo.png');
export const SUSHIlogo: ImageSourcePropType = require('../../assets/images/sushi-logo.png');
export const YFIlogo: ImageSourcePropType = require('../../assets/images/yfi-logo.png');
export const DPIlogo: ImageSourcePropType = require('../../assets/images/dpi-logo.png');
export const MVIlogo: ImageSourcePropType = require('../../assets/images/mvi-logo.png');
