echo \
"STACKUP_BACKUP_PORT=${STACKUP_BACKUP_PORT:-3001}
STACKUP_BACKUP_MONGODB_URL=${STACKUP_BACKUP_MONGODB_URL:-mongodb://127.0.0.1:27018/app}
STACKUP_BACKUP_SENTRY_DSN=${STACKUP_BACKUP_SENTRY_DSN}
STACKUP_BACKUP_ALCHEMY_POLYGON_RPC=${STACKUP_BACKUP_ALCHEMY_POLYGON_RPC}" \
> .env

echo "Env files successfully generated."
