echo \
"STACKUP_EXPLORER_PORT=${STACKUP_EXPLORER_PORT:-3000}
STACKUP_EXPLORER_MONGODB_URL=${STACKUP_EXPLORER_MONGODB_URL:-mongodb://127.0.0.1:27017/app}
STACKUP_EXPLORER_SENTRY_DNS=${STACKUP_EXPLORER_SENTRY_DNS}
STACKUP_EXPLORER_ALCHEMY_POLYGON_RPC=${STACKUP_EXPLORER_ALCHEMY_POLYGON_RPC}" \
> .env

echo "Env files successfully generated."
