echo \
"STACKUP_EXPLORER_PORT=${STACKUP_EXPLORER_PORT:-3000}
STACKUP_EXPLORER_NETWORK_ENV=${STACKUP_EXPLORER_NETWORK_ENV:-testnet}
STACKUP_EXPLORER_MONGODB_URL=${STACKUP_EXPLORER_MONGODB_URL:-mongodb://127.0.0.1:27017/app}
STACKUP_EXPLORER_SENTRY_DSN=${STACKUP_EXPLORER_SENTRY_DSN}
STACKUP_EXPLORER_COINMARKETCAP_API_KEY=${STACKUP_EXPLORER_COINMARKETCAP_API_KEY}
STACKUP_EXPLORER_BLOCKNATIVE_API_KEY=${STACKUP_EXPLORER_BLOCKNATIVE_API_KEY}
STACKUP_EXPLORER_ALCHEMY_POLYGON_RPC=${STACKUP_EXPLORER_ALCHEMY_POLYGON_RPC}
STACKUP_EXPLORER_POLYGONSCAN_API_KEY=${STACKUP_EXPLORER_POLYGONSCAN_API_KEY}" \
> .env

echo "Env files successfully generated."
