name: Contracts

on:
  push:
    branches: [master]
    paths:
      - "./apps/contracts/**"
  pull_request:
    branches: [master]
    paths:
      - "./apps/contracts/**"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn workspace @stackupfinance/contracts run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./apps/contracts/coverage/coverage-final.json
          flags: contracts
          fail_ci_if_error: true
