name: WalletJS

on:
  push:
    branches: [main]
    paths:
      - "packages/walletjs/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/walletjs/**"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn workspace @stackupfinance/walletjs run test
